language: ruby

sudo: required

services:
  - docker

rvm:
  - 2.2
  - 2.3.0
matrix:
  allow_failures:
    - rvm: 2.3.0
  fast_finish: true

before_install:
  - bundle install
bundler_args: --without development
cache: bundler

script:
  - bundle exec rake
  - docker build -t appdax/cc-fetcher .
  - docker ps -a
  - docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - docker push appdax/cc-fetcher
