install: true

sudo: false

services:
  - docker

script:
  - docker build -t appdax/cc-fetcher:test -f Dockerfile.test .
  - docker run -e CODECLIMATE_REPO_TOKEN=$CODECLIMATE_REPO_TOKEN -t appdax/cc-fetcher:test
  - docker rmi -f appdax/cc-fetcher:test
  - docker build -t appdax/cc-fetcher:edge -f Dockerfile.prod .
  - docker ps -a
  - docker images --filter "dangling=false"

after_success:
  - docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - docker push appdax/cc-fetcher
