language: ruby

sudo: required

services:
  - docker

rvm:
  - 2.2
matrix:
  fast_finish: true

script:
  - docker build -t appdax/cc-fetcher:test -f Dockerfile.test .
  - docker run --rm -e CODECLIMATE_REPO_TOKEN=$CODECLIMATE_REPO_TOKEN appdax/cc-fetcher:test
  - docker build -t appdax/cc-fetcher:edge -f Dockerfile.prod .
  - docker ps -a
  - docker images --filter "dangling=false"
  - docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - docker push appdax/cc-fetcher
